### ISSUE TITLE
Publint fails for published module

### ISSUE THREAD

**Issue by manniL** [contentstack/contentstack-typescript#35]
Hey all 👋🏻

I've noticed that [publint](https://publint.dev/@contentstack/delivery-sdk@4.0.6) fails for your currently published module, mostly due to CJS/ESM issues.
While tackling, supporting the standardized `exports` field would be extremely helpful (and future-proof) too ☺️

Further read @ https://github.com/frehner/modern-guide-to-packaging-js-library

**Comment by cs-raj** [comment]
Hi @manniL thanks for raising this. We will be looking into this in the upcoming sprint.
cc: @netrajpatel @shafeeqd959 @harshithad0703 @sunil-lakshman

**Comment by timbenniks** [comment]
@manniL see: https://publint.dev/@contentstack/delivery-sdk@4.4.1 we have released a new version that works like magic now...

**Comment by manniL** [comment]
Sweet, that looks way better! 👏🏻
